"""add_nutrient_requirements_table

Revision ID: a36ce9c7da17
Revises: 91ceeba6fb9b
Create Date: 2025-05-30 14:17:39.294272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36ce9c7da17'
down_revision: Union[str, None] = '91ceeba6fb9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrient_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrient_requirement_name', sa.String(), nullable=False),
    sa.Column('nutrient_requirement_description', sa.String(), nullable=True),
    sa.Column('composition', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrient_requirements_id'), 'nutrient_requirements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrient_requirements_id'), table_name='nutrient_requirements')
    op.drop_table('nutrient_requirements')
    # ### end Alembic commands ###
