"""added ingredients table

Revision ID: b07fafefb595
Revises: 0ae601d97291
Create Date: 2025-05-27 20:46:13.181604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07fafefb595'
down_revision: Union[str, None] = '0ae601d97291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('crude_protein', sa.Float(), nullable=False),
    sa.Column('crude_fat', sa.Float(), nullable=False),
    sa.Column('crude_fiber', sa.Float(), nullable=False),
    sa.Column('metabolized_energy', sa.Float(), nullable=False),
    sa.Column('calcium', sa.Float(), nullable=False),
    sa.Column('total_phosphorus', sa.Float(), nullable=False),
    sa.Column('avail_phosphorus', sa.Float(), nullable=False),
    sa.Column('lysine', sa.Float(), nullable=False),
    sa.Column('methionine', sa.Float(), nullable=False),
    sa.Column('m_c', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
